[package]
edition = "2021"
name = "rats-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ciborium = "0.2.2"
hex = "0.4.3"
occlum_dcap = {git = "https://github.com/occlum/occlum", tag = "v0.29.7", optional = true}
p256 = {version = "0.13.2", optional = true}
pkcs8 = {version = "0.10.2", features = ["pem"], optional = true}
rand = "0.8.5"
rsa = {version = "0.9.6", features = ["sha2"], optional = true}
serde = {version = "1.0", features = ["derive"]}
serde_bytes = "0.11.14"
sha2 = {version = "0.10.8", features = ["oid"], optional = true}
spdmlib = {git = "https://github.com/ccc-spdm-tools/spdm-rs", branch = "main", optional = true, features = ["spdm-ring", "hashed-transcript-data"]}
thiserror = "1.0.56"
x509-cert = {version = "0.2.5", features = ["builder"], optional = true}
zeroize = "1.7.0"

[patch."https://github.com/ccc-spdm-tools/spdm-rs"]
spdmlib = {path = '../spdm-rs/spdmlib'}

[features]
build-mode-host = []
build-mode-occlum = ["dep:occlum_dcap"]
build-mode-sgx = []
crypto-rustcrypto = ["dep:x509-cert", "dep:sha2", "dep:p256", "dep:rsa", "dep:pkcs8"]
default = ["build-mode-occlum", "crypto-rustcrypto"]
transport-spdm = ["dep:spdmlib"]
