name: Basic Compilation Check

on: [push, pull_request]

jobs:
  build-and-test:
    container: ghcr.io/imlk0/rats-rs:master

    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # https://github.com/actions/checkout/issues/116#issuecomment-644419389

      - name: Prepare spdm-rs
        run:
          cd deps/spdm-rs && sh_script/pre-build.sh
        env:
          HOME: /root

      - name: Compile ${{ github.repository }}
        run:
          cargo build
        env:
          HOME: /root

      - name: Run unit test ${{ github.repository }}
        run:
          just run-test-in-host
        env:
          HOME: /root
